### ISSUE TITLE
Trying out CSS variables

### ISSUE THREAD

**Issue by zannain** [johnnyd/colmar#4]
Props for using SASS in this mockup. Preprocessors were created to make up for the lack of feature of CSS that are found in other programming languages such as variables and computations. Recently, however, CSS introduced variables which eliminate the need to use a preprocessor, at least when it comes to using variables. Here's an article that elaborates on this as well as the few benefits of using [CSS variables over a preprocessor](https://css-tricks.com/difference-between-types-of-css-variables/)

```css
:root {
    --main-font-size: 1.75rem;
    --main-font-style: bold;
}

h1 {
     font-size: var(--main-font-size);
}

.className {
    font-weight: var(--main-font-style);
}
```
